/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.13.0+p3-g40b6564e
 *
 * Project: 'rylr900_swd.Debug+STM32L151C8TxA' 
 * Target:  'Debug+STM32L151C8TxA' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32l1xx.h"

/* Keil::Device&Standalone:Startup@1.0.0 */
#define RTE_DEVICE_STARTUP_STM32L1XX    /* Device Startup for STM32L1 */


#endif /* RTE_COMPONENTS_H */
